/* English names for folders, files and programs on the practice PC.
   Shared by the program code (via T()) and the English courses in js/en/, which use the
   English names directly. Change a name here and in the courses at the same time. */
Object.assign(I18N.en, {
  /* Programs (as in the taskbar, Start menu and window titles) */
  'Filutforsker': 'File Explorer',
  'Skriv': 'Write',
  'Nettleser': 'Browser',
  'Innleveringer': 'Assignments',
  'Papirkurv': 'Recycle Bin',
  'Filvisning': 'File Viewer',
  'Innstillinger': 'Settings',
  'Oppgavebehandling': 'Task Manager',
  'Terminal': 'Terminal',
  'Kode': 'Code',
  'Notater': 'Notes',
  'E-post': 'Mail',
  'Skrivetrening': 'Typing Practice',
  'Firmaportalen': 'Company Portal',
  'Introduksjon': 'Introduction',

  /* The default user name and the other course page */
  'Elev': 'Student',
  'programmering.html': 'programming.html',

  /* System folders */
  'Denne PC-en': 'This PC',
  'Skrivebord': 'Desktop',
  'Dokumenter': 'Documents',
  'Nedlastinger': 'Downloads',
  'Bilder': 'Pictures',
  'Ny mappe': 'New folder',
  ' - Kopi': ' - Copy',

  /* Folders */
  'Skole': 'School',
  'Norsk': 'Norwegian',
  'Matte': 'Maths',
  'Engelsk': 'English',
  'Naturfag': 'Science',
  'Samfunnsfag': 'Social studies',
  'Gammelt': 'Old',
  'Prosjekter': 'Projects',
  'Klassetur': 'Class trip',
  'Min mappe': 'My folder',
  '7. trinn': 'Year 7',
  'Mine prosjekter': 'My projects',
  'Programmering': 'Programming',

  /* Files */
  'Klassetur-budsjett.xlsx': 'Class-trip-budget.xlsx',
  'Sommerprosjekt.docx': 'Summer-project.docx',
  'Leksjon-1.pptx': 'Lesson-1.pptx',
  'Notater-7-trinn.txt': 'Notes-year-7.txt',
  'Dokument (3).docx': 'Document (3).docx',
  'Dokument (7).docx': 'Document (7).docx',
  'Dokument1.docx': 'Document1.docx',
  'Dokument12.docx': 'Document12.docx',
  'Fotosyntese.pptx': 'Photosynthesis.pptx',
  'Matteprøve.pdf': 'Maths-test.pdf',
  'gammel-liste.txt': 'old-list.txt',
  'skjema.pdf': 'form.pdf',
  'Klassebilde.jpg': 'Class-photo.jpg',
  'Tur-til-fjellet.jpg': 'Mountain-trip.jpg',
  'Skogen.jpg': 'Forest.jpg',
  'Oppgaveark-brøk.pdf': 'Worksheet-fractions.pdf',
  'Mal-rapport.docx': 'Report-template.docx',
  'Demokrati.pptx': 'Democracy.pptx',
  'Bokrapport-mal.docx': 'Book-report-template.docx',
  'Ukeplan-uke-39.pdf': 'Weekly-plan-week-39.pdf',
  'Presentasjon-uke-39.pptx': 'Presentation-week-39.pptx',
  'Nytt tekstdokument.txt': 'New Text Document.txt',
  'Nytt Microsoft Word-dokument.docx': 'New Microsoft Word Document.docx',
  'Ny Microsoft PowerPoint-presentasjon.pptx': 'New Microsoft PowerPoint Presentation.pptx',
  'Nytt Microsoft Excel-regneark.xlsx': 'New Microsoft Excel Worksheet.xlsx',
  'ny.py': 'new.py',
  'nytt-skript.ps1': 'new-script.ps1',
  'Min-del-samfunnsfag.docx': 'My-part-social-studies.docx',
  'Viktig-innlevering.docx': 'Important-assignment.docx',
  'Mesterprove.docx': 'Master-test.docx',
  'Oppsett.docx': 'Layout.docx',
  'Rapport-fotosyntese.docx': 'Report-photosynthesis.docx',
  'dokument44.docx': 'document44.docx',
  'Tastaturprove.docx': 'Keyboard-test.docx',
  'Tastatur-øving.docx': 'Keyboard-practice.docx',
  'Gruppeoppgave.docx': 'Group-project.docx',
  'Ukesnotat.docx': 'Weekly-note.docx',
  'Dikt-analyse.docx': 'Poem-analysis.docx',
  'Dikt.docx': 'Poem.docx',
  'Norsk-diktanalyse-Nordlys.docx': 'Norwegian-poem-analysis-Northern-Lights.docx',
  'Mitt første dokument.docx': 'My first document.docx',
  'Mitt første dokument.txt': 'My first document.txt',
  'Huskeliste.txt': 'Reminders.txt',
  'Rapport.docx': 'Report.docx',
  'rapport.docx': 'report.docx',
  'Fremføring.pptx': 'Talk.pptx',
  'Budsjett.xlsx': 'Budget.xlsx',
  'Notat.docx': 'Note.docx',
  'Formatering.docx': 'Formatting.docx',
  'Ukeplan.docx': 'Weekly-plan.docx',
  'Engelsk-gloser-uke-3.docx': 'English-vocabulary-week-3.docx',
  'Engelsk-London-tekst.docx': 'English-London-text.docx',
  'Naturfag-labrapport.docx': 'Science-lab-report.docx',
  'Naturfag-rapport-fotosyntese.docx': 'Science-report-photosynthesis.docx',
  'Matte-oppgaver-kap2.pdf': 'Maths-exercises-ch2.pdf',
  'Norsk-fortelling.docx': 'Norwegian-story.docx',
  'ny.docx': 'new.docx',
  'uke-fil.txt': 'week-file.txt',
  'slett-meg.txt': 'delete-me.txt',
  'flytt-meg.txt': 'move-me.txt',
  'angre-meg.txt': 'undo-me.txt',
  'prove-a.txt': 'test-a.txt',
  'prove-b.txt': 'test-b.txt',
  'prove-c.txt': 'test-c.txt',
  'kopi.py': 'copy.py',
  'hilsen.py': 'greeting.py',
  'alder.py': 'age.py',
  'feil1.py': 'error1.py',
  'feil2.py': 'error2.py',
  'evig.py': 'forever.py',
  'navn.txt': 'name.txt',
  'resultat.txt': 'result.txt',
  'hei.ps1': 'hello.ps1',
  'notat.txt': 'note.txt',
  'notat-kopi.txt': 'note-copy.txt',
  'mester.py': 'master.py',
  'mesterfeil.py': 'master-bug.py',
  'mester.ps1': 'master.ps1',
  'uke.txt': 'week.txt',
  'uke.py': 'week.py',
  'ukesfeil.py': 'week-bug.py',
  'uke.ps1': 'week.ps1'
});
