/* English texts for the program code. The key is the Norwegian text exactly as it is written
   in the code (T('...')); names of programs, folders and files are in names.js. */
Object.assign(I18N.en, {
  /* Desktop, windows, dialogs, file system, guide panel and introduction */
  "Fant ikke mappen.": "Couldn't find the folder.",
  "Mappen «{0}» er full (maks {1} elementer). Slett noe, eller bruk en annen mappe.": "The folder \"{0}\" is full (max {1} items). Delete something, or use a different folder.",
  "Øvings-PC-en er full (maks {0} filer og mapper til sammen). Slett noe og tøm papirkurven.": "The practice PC is full (max {0} files and folders in total). Delete something and empty the Recycle Bin.",
  "Du kan ikke lage mapper dypere enn {0} nivåer.": "You can't make folders more than {0} levels deep.",
  "Øvings-PC-en har ikke mer lagringsplass. Slett noen filer først.": "The practice PC has no more storage space. Delete some files first.",
  "Du må skrive inn et navn.": "You need to type a name.",
  "Et navn kan ikke inneholde disse tegnene:  \\ / : * ? \" < > |": "A name can't contain any of these characters:  \\ / : * ? \" < > |",
  "Navnet er for langt (maks {0} tegn).": "The name is too long (max {0} characters).",
  "Det finnes allerede en mappe eller fil med navnet «{0}» her.": "There's already a folder or file called \"{0}\" here.",
  "Det finnes allerede en fil med navnet «{0}» her.": "There's already a file called \"{0}\" here.",
  "Fant ikke filen.": "Couldn't find the file.",
  "Denne mappen kan ikke få nytt navn.": "This folder can't be renamed.",
  "Det finnes allerede en fil eller mappe med navnet «{0}» her.": "There's already a file or folder called \"{0}\" here.",
  "Du kan ikke flytte en mappe inn i seg selv.": "You can't move a folder into itself.",
  "Denne mappen kan ikke flyttes.": "This folder can't be moved.",
  "Du kan ikke kopiere en mappe inn i seg selv.": "You can't copy a folder into itself.",
  "Denne mappen kan ikke slettes.": "This folder can't be deleted.",
  "Nettleseren har ikke plass til å lagre flere filer. Slett noe, eller tøm papirkurven.": "The browser has no room to save more files. Delete something, or empty the Recycle Bin.",
  "Sommerprosjekt – planter i skolegården\n\nVi plantet solsikker og målte hvor fort de vokste.": "Summer project – plants in the school garden\n\nWe planted sunflowers and measured how fast they grew.",
  "Husk: gymtøy på tirsdager.\nInnlevering naturfag fredag.": "Remember: PE kit on Tuesdays.\nScience homework due Friday.",
  "Analyse av diktet «Nordlys»\n\nDiktet handler om lyset som danser over himmelen om vinteren. Dikteren bruker mange bilder ...": "Analysis of the poem \"Northern Lights\"\n\nThe poem is about the light that dances across the sky in winter. The poet uses a lot of imagery ...",
  "melk\nbrød\nost\nepler": "milk\nbread\ncheese\napples",
  "Du har for mange vinduer åpne (maks {0}). Lukk noen vinduer først.": "You have too many windows open (max {0}). Close some windows first.",
  "Minimer": "Minimise",
  "Maksimer": "Maximise",
  "Lukk": "Close",
  "Gjenopprett": "Restore",
  "tittellinjen til vinduet «{0}»": "the title bar of the \"{0}\" window",
  "Gjenopprett ned": "Restore Down",
  "Programmer og funksjoner": "Installed apps",
  "Slå av eller logg av": "Shut down or sign out",
  "Logg av": "Sign out",
  "På en ekte PC logger dette deg av. Øvings-PC-en fortsetter.": "On a real PC this signs you out. The practice PC keeps going.",
  "Slå av": "Shut down",
  "På en ekte PC slår dette av maskinen. Husk å lagre først!": "On a real PC this turns the computer off. Remember to save first!",
  "Start på nytt": "Restart",
  "På en ekte PC starter maskinen på nytt nå.": "On a real PC the computer would restart now.",
  "Start-knappen": "the Start button",
  "Løsne fra oppgavelinjen": "Unpin from taskbar",
  "Fest til oppgavelinjen": "Pin to taskbar",
  "Lukk alle vinduer": "Close all windows",
  "Lukk vindu": "Close window",
  "{0}-ikonet i oppgavelinjen": "the {0} icon on the taskbar",
  "Innstillinger for oppgavelinjen": "Taskbar settings",
  "Vis skrivebordet": "Show desktop",
  "oppgavelinjen": "the taskbar",
  "Fullskjerm av/på (F11)": "Full screen on/off (F11)",
  "English version": "Norsk utgave (Norwegian)",
  "Ja": "Yes",
  "Nei": "No",
  "Avbryt": "Cancel",
  "<p><b>Vil du lagre endringene i «{0}»?</b></p><p class=\"muted\">Hvis du ikke lagrer, forsvinner det du har skrevet.</p>": "<p><b>Do you want to save your changes to \"{0}\"?</b></p><p class=\"muted\">If you don't save, what you've written will be lost.</p>",
  "Lagre": "Save",
  "Ikke lagre": "Don't save",
  "Alle filer (*.*)": "All files (*.*)",
  "Tilbake": "Back",
  "Opp ett nivå": "Up one level",
  "Filnavn:": "File name:",
  "Velg en mappe i listen, eller stå i mappen du vil bruke": "Select a folder in the list, or go into the folder you want to use",
  "Navn": "Name",
  "Endringsdato": "Date modified",
  "Størrelse": "Size",
  "Ingen elementer samsvarer med søket.": "No items match your search.",
  "Navn på mappen:": "Folder name:",
  "Det finnes allerede en mappe med dette navnet.": "There's already a folder with this name.",
  "Lagre som": "Save As",
  "Åpne": "Open",
  "Velg mappe": "Select Folder",
  "Det finnes en mappe med dette navnet.": "There's a folder with this name.",
  "Bekreft Lagre som": "Confirm Save As",
  "«{0}» finnes allerede. Vil du erstatte den?": "\"{0}\" already exists. Do you want to replace it?",
  "Finner ikke filen «{0}» i denne mappen.": "Can't find the file \"{0}\" in this folder.",
  "Velg en fil først.": "Select a file first.",
  "Hopp over": "Skip",
  "Neste": "Next",
  "Kom i gang": "Get started",
  "Plassering": "Location",
  "Inneholder": "Contains",
  "{0} filer, {1} mapper": "{0} Files, {1} Folders",
  "Endret": "Modified",
  "Åpnes med": "Opens with",
  "Egenskaper for {0}": "{0} Properties",
  "Tøm papirkurv": "Empty Recycle Bin",
  "Egenskaper": "Properties",
  "{0}-ikonet på skrivebordet": "the {0} icon on the desktop",
  "{0} på skrivebordet": "{0} on the desktop",
  "Angret.": "Undone.",
  "Skjerminnstillinger": "Display settings",
  "Tilpass": "Personalise",
  "Standard bakgrunn": "Default background",
  "Velg et bilde …": "Choose a picture …",
  "Høyreklikk på et bilde i Filutforsker og velg «Angi som skrivebordsbakgrunn».": "Right-click a picture in File Explorer and choose \"Set as desktop background\".",
  "skrivebordet (bakgrunnen)": "the desktop (background)",
  "Bakgrunnen er tilbakestilt.": "The background has been reset.",
  "«{0}» er nå skrivebordsbakgrunn.": "\"{0}\" is now the desktop background.",
  "Nettleseren tillot ikke fullskjerm her. Trykk F11 for å slå på fullskjerm.": "The browser didn't allow full screen here. Press F11 to turn on full screen.",
  "<p class=\"fso-sub\">Øvings-PC for skolen. Dette er en simulering i nettleseren, ikke en ekte PC.</p><p>Klikk hvor som helst for å starte i fullskjerm.</p><p class=\"fso-tip\">Tips: <kbd>F11</kbd> slår fullskjerm av og på. <kbd>Esc</kbd> avslutter fullskjerm.</p>": "<p class=\"fso-sub\">A practice PC for school. This is a simulation in your browser, not a real PC.</p><p>Click anywhere to start in full screen.</p><p class=\"fso-tip\">Tip: <kbd>F11</kbd> turns full screen on and off. <kbd>Esc</kbd> exits full screen.</p>",
  "Avslutt fullskjerm (Esc eller F11)": "Exit full screen (Esc or F11)",
  "Fullskjerm (F11)": "Full screen (F11)",
  "Nullstill øvings-PC-en": "Reset the practice PC",
  "Siden har fått flere feil. Hvis den henger, nullstill øvings-PC-en.": "The page has had several errors. If it freezes, reset the practice PC.",
  "Noe gikk galt under oppstart. Nullstill øvings-PC-en for å komme i gang igjen.": "Something went wrong during start-up. Reset the practice PC to get going again.",
  "Veilederen kunne ikke starte. Nullstill øvings-PC-en for å komme i gang igjen.": "The guide couldn't start. Reset the practice PC to get going again.",
  "Hva heter du?": "What's your name?",
  "Fornavn og etternavn": "First name and surname",
  "<p class=\"muted\">Navnet brukes bare til å vise fremdriften din, og lagres på denne maskinen.</p>": "<p class=\"muted\">Your name is only used to show your progress, and is saved on this computer.</p>",
  "Velkommen til programmeringskurset": "Welcome to the programming course",
  "Velkommen til Datatrening": "Welcome to Datatrening",
  "<p>Her lærer du å bruke <b>terminalen</b>, skrive kode i en <b>editor</b> og kjøre programmene dine, slik det gjøres på en ekte PC.</p>": "<p>Here you'll learn to use the <b>terminal</b>, write code in an <b>editor</b> and run your programs, just like on a real PC.</p>",
  "<p>Kurset bygger på grunnkurset om filer og mapper. Kan du ikke det ennå, ta det først.</p>": "<p>This course builds on the basic course about files and folders. If you don't know that yet, do it first.</p>",
  "<p>Her lærer du å bruke en PC slik vi gjør på skolen: <b>filer og mapper</b>, lagring, formatering, e-post, notater og innlevering.</p>": "<p>Here you'll learn to use a PC the way we do at school: <b>files and folders</b>, saving, formatting, email, notes and handing in work.</p>",
  "<p>Alt skjer på en <b>øvings-PC</b> inne i nettleseren. Den ser ut som en vanlig Windows-PC, men den er en simulering.": "<p>Everything happens on a <b>practice PC</b> inside your browser. It looks like a normal Windows PC, but it's a simulation.",
  "<b>Du kan ikke ødelegge noe.</b> Alt du gjør her, skjer bare her.</p>": "<b>You can't break anything.</b> Whatever you do here only happens here.</p>",
  "Skriv navnet ditt, så vet læreren hvem fremdriften tilhører.": "Type your name so your teacher knows whose progress this is.",
  "Slik lærer du": "How you learn",
  "<p>Panelet til <b>høyre</b> viser ett oppdrag om gangen, delt opp i små steg.</p>": "<p>The panel on the <b>right</b> shows one task at a time, split into small steps.</p>",
  "<li>Stegene blir <b>grønne av seg selv</b> når du gjør dem riktig på øvings-PC-en. Du trenger ikke trykke «ferdig».</li>": "<li>The steps turn <b>green by themselves</b> when you do them correctly on the practice PC. You don't need to press \"done\".</li>",
  "<li>Noen steg er <b>spørsmål</b>. Teorispørsmålene kommer først i hvert kurs, og svaret står i <b>«Les først»</b>-boksen øverst.</li>": "<li>Some steps are <b>questions</b>. The theory questions come first in each course, and the answer is in the <b>\"Read first\"</b> box at the top.</li>",
  "<li>Svarer du feil på et teorispørsmål, må du innom teksten før du kan prøve igjen. Det er med vilje.</li>": "<li>If you get a theory question wrong, you have to go back to the text before you can try again. That's on purpose.</li>",
  "<p>Når du har gjort alle oppdragene i et kurs, får du en <b>mesterprøve</b>. Der får du bare mål, ingen oppskrift og ingen hint.</p>": "<p>When you've done all the tasks in a course, you get a <b>master test</b>. It only gives you goals – no instructions and no hints.</p>",
  "Hvis du står fast": "If you get stuck",
  "<li>Klikk <b>«Vis hint»</b> på steget du står på. Hintet forteller deg hvor du skal se.</li>": "<li>Click <b>\"Show hint\"</b> on the step you're on. The hint tells you where to look.</li>",
  "<li>Åpne <b>«Les først»</b> øverst i oppdraget. Der står teorien du trenger.</li>": "<li>Open <b>\"Read first\"</b> at the top of the task. It has the theory you need.</li>",
  "<li>Du kan alltid <b>starte oppdraget på nytt</b> med knappen nederst i panelet.</li>": "<li>You can always <b>restart the task</b> with the button at the bottom of the panel.</li>",
  "<li>Henger øvings-PC-en? Fanen <b>Fremdrift</b> har en knapp som tilbakestiller den uten å slette fremdriften din.</li>": "<li>Practice PC frozen? The <b>Progress</b> tab has a button that resets it without deleting your progress.</li>",
  "<p>Og så er det helt greit å spørre læreren. Si <b>hva du gjorde</b>, <b>hva som skjedde</b> og <b>hva som står på skjermen</b>, så er det lett å hjelpe deg.</p>": "<p>And it's absolutely fine to ask your teacher. Say <b>what you did</b>, <b>what happened</b> and <b>what it says on the screen</b>, and then it's easy to help you.</p>",
  "<li>Programmene ligger nederst i <b>oppgavelinjen</b> og i <b>Start-menyen</b>.</li>": "<li>The apps are at the bottom in the <b>taskbar</b> and in the <b>Start menu</b>.</li>",
  "<li><kbd>F11</kbd> slår fullskjerm av og på. <kbd>Esc</kbd> avslutter fullskjerm.</li>": "<li><kbd>F11</kbd> turns full screen on and off. <kbd>Esc</kbd> exits full screen.</li>",
  "<li>Fanen <b>Kurs</b> viser alle kursene. Ta dem gjerne i rekkefølge.</li>": "<li>The <b>Courses</b> tab shows all the courses. It's a good idea to take them in order.</li>",
  "<li>Når du har fullført et kurs, dukker <b>Ukens øving</b> opp. Den holder ferdighetene ved like.</li>": "<li>When you've finished a course, <b>Weekly practice</b> appears. It keeps your skills fresh.</li>",
  "<p class=\"wiz-tip\">💡 Du finner denne introduksjonen igjen når som helst under <b>Start-menyen → Introduksjon</b>.</p>": "<p class=\"wiz-tip\">💡 You can find this introduction again at any time under <b>Start menu → Introduction</b>.</p>",
  "Start første oppdrag": "Start the first task",
  "Lukket fra forrige oppdrag: {0}. Du starter med blanke ark.": "Closed from the last task: {0}. You're starting with a clean slate.",
  "Fullfør et kurs først, så kan du repetere det du har lært.": "Finish a course first, then you can revise what you've learnt.",
  "🎉 Oppdrag fullført: {0}": "🎉 Task complete: {0}",
  "🏅 Mesterprøve bestått: {0}": "🏅 Master test passed: {0}",
  "Ukens øving fullført!": "Weekly practice complete!",
  "Lær å bruke PC": "Learn to use a PC",
  "{0} sekunder": "{0} seconds",
  "{0} min {1} s": "{0} min {1} s",
  "<p>Du har ikke startet noe oppdrag ennå.</p>": "<p>You haven't started a task yet.</p>",
  "Gå til kursene": "Go to the courses",
  "<p>Fant ikke oppdraget.</p>": "<p>Couldn't find the task.</p>",
  "<div class=\"ktag\">Kurs {0} · {1}</div><h2>Oppdrag {0}.{2}: {3}</h2>": "<div class=\"ktag\">Course {0} · {1}</div><h2>Task {0}.{2}: {3}</h2>",
  "Teori": "Theory",
  "Spørsmål": "Question",
  "Ikke riktig. Spørsmålet er låst til du har lest teksten. Trykk på knappen nederst i teksten for å komme tilbake og svare på nytt.": "Not right. The question is locked until you've read the text. Press the button at the bottom of the text to come back and answer again.",
  "📖 Gå til «Les først»-teksten": "📖 Go to the \"Read first\" text",
  "Ikke helt riktig. {0}": "Not quite right. {0}",
  "Prøv igjen!": "Try again!",
  "Svar: {0}": "Answer: {0}",
  "Skjul hint": "Hide hint",
  "Vis hint": "Show hint",
  "Bra jobbet! Du fullførte «{0}».": "Well done! You finished \"{0}\".",
  "Neste oppdrag →": "Next task →",
  "🏅 Ta mesterprøven": "🏅 Take the master test",
  "Neste kurs →": "Next course →",
  "Se fremdriften din": "See your progress",
  "Start oppdraget på nytt": "Restart the task",
  "Kursoversikt": "Course overview",
  "📖 Les først: {0}": "📖 Read first: {0}",
  "Jeg har lest teksten": "I've read the text",
  "Les teksten over … ({0} s)": "Read the text above … ({0} s)",
  "Jeg har lest teksten, tilbake til spørsmålet": "I've read the text – back to the question",
  "Spørsmålet er låst til du har lest teksten. Knappen under blir aktiv når lesetiden er over.": "The question is locked until you've read the text. The button below becomes active when the reading time is up.",
  "<div class=\"ktag\">Kurs {0} · {1}</div><h2>🏅 Mesterprøve: {2}</h2>": "<div class=\"ktag\">Course {0} · {1}</div><h2>🏅 Master test: {2}</h2>",
  "Her får du ingen oppskrift og ingen hint. Men du får slå opp: teorien ligger under, slik du kan slå opp i en bok eller på nettet når du jobber på ekte. Målene hukes av etter hvert som du klarer dem, i den rekkefølgen du vil.": "No instructions and no hints this time. But you can look things up: the theory is below, just like you can look things up in a book or online when you work for real. The goals are ticked off as you manage them, in any order you like.",
  "📖 Slå opp: {0}": "📖 Look up: {0}",
  "Mesterprøven er bestått!": "You passed the master test!",
  "Tid: {0}": "Time: {0}",
  "Start prøven på nytt": "Restart the test",
  "Jeg trenger å øve mer": "I need more practice",
  "<h3>💻 Gjør det på din egen PC</h3><p class=\"muted\">Øvings-PC-en er en simulering. Gjør det samme på den ekte maskinen din, så sitter det. Huk av når du har gjort det.</p>": "<h3>💻 Do it on your own PC</h3><p class=\"muted\">The practice PC is a simulation. Do the same thing on your real computer and it'll stick. Tick it off when you've done it.</p>",
  "<div class=\"ktag\">Ukens øving</div><h2>Oppgave {0} av {1}</h2>": "<div class=\"ktag\">Weekly practice</div><h2>Exercise {0} of {1}</h2>",
  "Du klarte {0} av {1}.": "You got {0} out of {1}.",
  "Ny øving": "New practice",
  "Fra kurset «{0}»": "From the course \"{0}\"",
  "<p class=\"muted\">Ingen hint denne gangen. Prøv først på egen hånd, og slå opp i teorien hvis du står fast.</p>": "<p class=\"muted\">No hints this time. Try on your own first, and look up the theory if you get stuck.</p>",
  "Avslutt øvingen": "End the practice",
  "🔁 Ukens øving": "🔁 Weekly practice",
  "aldri tatt": "never done",
  "tatt i dag": "done today",
  "{0} dager siden": "{0} days ago",
  "Fem tilfeldige oppgaver fra kursene du har fullført, uten hint. Hold ferdighetene ved like.": "Five random exercises from the courses you've finished, without hints. Keep your skills fresh.",
  "Start ukens øving": "Start weekly practice",
  "Ta en øving til": "Do another practice",
  "<p class=\"muted\">Velg et kurs. Det er lurt å ta dem i rekkefølge. Klikk på et oppdrag for å starte det.</p>": "<p class=\"muted\">Choose a course. It's a good idea to take them in order. Click a task to start it.</p>",
  "🔒 Svar på teorispørsmålene i oppdrag {0}.1 først. Da låses resten av kurset opp.": "🔒 Answer the theory questions in task {0}.1 first. That unlocks the rest of the course.",
  "Teorien først: svar på spørsmålene i oppdrag {0}.1, så åpner resten av kurset seg.": "Theory first: answer the questions in task {0}.1, and then the rest of the course opens up.",
  "Mesterprøve: {0}": "Master test: {0}",
  " (fullfør oppdragene først)": " (finish the tasks first)",
  "<p class=\"muted\" style=\"margin-top:16px\">Dette er kurssettet for programmering. <a href=\"{0}\">← Til grunnkurset</a> (filer, mapper, lagring, innlevering).</p>": "<p class=\"muted\" style=\"margin-top:16px\">These are the programming courses. <a href=\"{0}\">← To the basic course</a> (files, folders, saving, handing in work).</p>",
  "<p class=\"muted\" style=\"margin-top:16px\">For programmeringselever finnes et eget kurssett med terminal (PowerShell), Kode-editor og Python: <a href=\"{0}\">Programmeringskurset →</a></p>": "<p class=\"muted\" style=\"margin-top:16px\">For programming students there's a separate set of courses with the terminal (PowerShell), the Code editor and Python: <a href=\"{0}\">Programming course →</a></p>",
  "Datatrening – fremdrift for {0} ({1})\n{2} av {3} oppdrag fullført\n": "Datatrening – progress for {0} ({1})\n{2} of {3} tasks completed\n",
  " · mesterprøve bestått": " · master test passed",
  "\n\nKode til læreren (lim inn hele linjen):\n": "\n\nCode for your teacher (paste the whole line):\n",
  "Navn:": "Name:",
  "Skriv navnet ditt": "Type your name",
  "{0} av {1} oppdrag fullført": "{0} of {1} tasks completed",
  "{0} av {1} mesterprøver bestått": "{0} of {1} master tests passed",
  "🔁 Siste ukesøving": "🔁 Last weekly practice",
  "<h2>🏆 Diplom</h2><div><b>{0}</b> har fullført alle kursene og mesterprøvene i Datatrening og kan bruke PC-en til skolearbeid!</div>": "<h2>🏆 Certificate</h2><div><b>{0}</b> has completed all the courses and master tests in Datatrening and can use a PC for schoolwork!</div>",
  "Kopier rapport til læreren": "Copy report for your teacher",
  "Rapporten er kopiert. Lim den inn i en melding til læreren.": "The report has been copied. Paste it into a message to your teacher.",
  "Rapport": "Report",
  "<p class=\"muted\">Merk alt (Ctrl+A), kopier (Ctrl+C) og lim inn i en melding til læreren.</p>": "<p class=\"muted\">Select all (Ctrl+A), copy (Ctrl+C) and paste it into a message to your teacher.</p>",
  "Nullstill fremdrift": "Reset progress",
  "Er du sikker? Alle fullførte oppdrag blir slettet.": "Are you sure? All your completed tasks will be deleted.",
  "<h3>Hvis øvings-PC-en henger</h3><p class=\"muted\">Knappen under sletter alle filer og mapper på øvings-PC-en og legger tilbake de opprinnelige. Fremdriften beholdes. Det samme skjer om du åpner siden med <code>?nullstill</code> bak adressen.</p>": "<h3>If the practice PC freezes</h3><p class=\"muted\">The button below deletes all files and folders on the practice PC and puts the original ones back. Your progress is kept. The same thing happens if you open the page with <code>?reset</code> after the address.</p>",
  "Tilbakestill øvings-PC-en": "Reset the practice PC",
  "Slette alle filer og mapper på øvings-PC-en og starte den på nytt?": "Delete all files and folders on the practice PC and restart it?",
  "Fremdriften er nullstilt.": "Your progress has been reset.",
  "Høyreklikk på {0} ✓": "Right-clicked {0} ✓",
  "Filmappe": "File folder",
  "{0}-fil": "{0} File",
  "Fil": "File",
  "et passende program": "a suitable app",
  "Microsoft Word-dokument": "Microsoft Word Document",
  "Microsoft PowerPoint-presentasjon": "Microsoft PowerPoint Presentation",
  "Microsoft Excel-regneark": "Microsoft Excel Worksheet",
  "PDF-dokument": "PDF Document",
  "Tekstdokument": "Text Document",
  "MP4-videofil": "MP4 Video File",
  "MP3-lydfil": "MP3 Audio File",
  "ZIP-komprimert mappe": "Compressed (zipped) Folder",
  "JPG-bilde": "JPG File",
  "PNG-bilde": "PNG File",
  "Program": "Application",
  "Python-fil": "Python File",
  "PowerShell-skript": "Windows PowerShell Script",
  "JavaScript-fil": "JavaScript File",
  "HTML-dokument": "HTML Document",
  "CSS-fil": "CSS File",
  "JSON-fil": "JSON File",
  "Markdown-fil": "Markdown File",
  "CSV-fil": "CSV File",
  "Microsoft Edge (PDF-leser)": "Microsoft Edge (PDF reader)",
  "Notisblokk": "Notepad",
  "Filmer og TV": "Films & TV",
  "Mediespiller": "Media Player",
  "Filutforsker (pakk ut først)": "File Explorer (extract first)",
  "Visual Studio Code (kjøres med python)": "Visual Studio Code (run with python)",
  "Nettleseren": "the browser",

  /* File Explorer, Write, Browser and Assignments */
  "«{0}» ble flyttet til papirkurven.": "“{0}” was moved to the Recycle Bin.",
  "{0} elementer ble flyttet til papirkurven.": "{0} items were moved to the Recycle Bin.",
  "Mappe": "Folder",
  "Nytt tekstdokument": "New Text Document",
  "Nytt Microsoft": "New Microsoft",
  "Ny Microsoft": "New Microsoft",
  "nytt-skript": "new-script",
  "Gi nytt navn": "Rename",
  "Mappen heter fortsatt «{0}». Gi nytt navn: klikk én gang på mappen, trykk F2, skriv navnet og trykk Enter. (Eller høyreklikk → Gi nytt navn.)": "The folder is still called “{0}”. To rename it: click the folder once, press F2, type the name and press Enter. (Or right-click → Rename.)",
  "Filen heter fortsatt «{0}». Gi nytt navn: klikk én gang på filen, trykk F2, skriv navnet og trykk Enter. (Eller høyreklikk → Gi nytt navn.)": "The file is still called “{0}”. To rename it: click the file once, press F2, type the name and press Enter. (Or right-click → Rename.)",
  "Gjenopprettet.": "Restored.",
  "Slett permanent": "Delete permanently",
  "Slett fil": "Delete File",
  "Er du sikker på at du vil slette «{0}» for alltid?": "Are you sure you want to permanently delete “{0}”?",
  "Er du sikker på at du vil slette disse {0} elementene for alltid?": "Are you sure you want to permanently delete these {0} items?",
  "Er du sikker på at du vil slette dette elementet for alltid?": "Are you sure you want to permanently delete this item?",
  "Er du sikker på at du vil slette dette for alltid?": "Are you sure you want to permanently delete this?",
  "Slette for alltid?": "Delete permanently?",
  "Åpne i nytt vindu": "Open in new window",
  "{0} (simulert)": "{0} (simulated)",
  "Åpne med": "Open with",
  "Angi som skrivebordsbakgrunn": "Set as desktop background",
  "Pakk ut alle …": "Extract All…",
  "En ZIP-fil er en pakket mappe. På en ekte PC pakkes filene ut i en ny mappe her.": "A ZIP file is a compressed folder. On a real PC the files are extracted into a new folder here.",
  "Skriv ut": "Print",
  "«{0}» ble sendt til skriveren (simulert).": "“{0}” was sent to the printer (simulated).",
  "Klipp ut": "Cut",
  "Kopier": "Copy",
  "Kopier som bane": "Copy as path",
  "Kopierte banen: {0}": "Copied the path: {0}",
  "Del": "Share",
  "Slett": "Delete",
  "Lim inn": "Paste",
  "Oppdater": "Refresh",
  "Vis": "View",
  "Sorter etter": "Sort by",
  "Angre": "Undo",
  "Ny": "New",
  "Store ikoner": "Large icons",
  "Detaljer": "Details",
  "Vis filendelser": "File name extensions",
  "Type": "Type",
  "Stigende": "Ascending",
  "Synkende": "Descending",
  "Frem": "Forward",
  "Søk": "Search",
  "Søk i {0}": "Search {0}",
  "Ny ▾": "New ▾",
  "Sorter ▾": "Sort ▾",
  "Vis ▾": "View ▾",
  "Opprinnelig plassering": "Original location",
  "Ingen treff på «{0}».": "No results for “{0}”.",
  "Papirkurven er tom.": "The Recycle Bin is empty.",
  "Denne mappen er tom.": "This folder is empty.",
  "Ukjent": "Unknown",
  "{0} element": "{0} item",
  "{0} elementer": "{0} items",
  "{0} element valgt": "{0} item selected",
  "{0} elementer valgt": "{0} items selected",
  "Filendelser er skjult (Vis → Vis filendelser)": "File name extensions are hidden (View → File name extensions)",
  "Gjenopprett filen først for å åpne den.": "Restore the file first to open it.",
  "et tomt sted i mappen «{0}»": "an empty space in the folder “{0}”",
  "«{0}» i menyen til venstre": "“{0}” in the menu on the left",
  "mappen «{0}»": "the folder “{0}”",
  "filen «{0}»": "the file “{0}”",
  "{0} i papirkurven": "{0} in the Recycle Bin",
  "⚠ Filen ligger ikke i OneDrive. Bare filer i OneDrive kan deles med lenke, fordi de ligger i skyen. Flytt filen til OneDrive først, eller send den som vedlegg.": "⚠ This file isn’t in OneDrive. Only files in OneDrive can be shared with a link, because they’re stored in the cloud. Move the file to OneDrive first, or send it as an attachment.",
  "Hvem skal få tilgang?": "Who should have access?",
  "Alle i klassen 8A": "Everyone in class 8A",
  "Bare læreren": "Only the teacher",
  "Jonas og Kari (gruppa mi)": "Jonas and Kari (my group)",
  "Hva skal de få lov til?": "What can they do?",
  "Kan redigere (skrive i dokumentet)": "Can edit (write in the document)",
  "Kan bare lese": "Can view only",
  "<b>Lenke eller vedlegg?</b> En <b>lenke</b> peker til filen i OneDrive, så alle ser den samme filen og siste versjon. Et <b>vedlegg</b> er en kopi: hvis andre skriver i kopien, får ikke du endringene. Bruk lenke når dere skal samarbeide.": "<b>Link or attachment?</b> A <b>link</b> points to the file in OneDrive, so everyone sees the same file and the latest version. An <b>attachment</b> is a copy: if others write in the copy, you don’t get their changes. Use a link when you’re working together.",
  "Del «{0}»": "Share “{0}”",
  "Kopier lenke": "Copy link",
  "Filen må ligge i OneDrive for å kunne deles med lenke.": "The file must be in OneDrive to be shared with a link.",
  "Lenken er kopiert. Lim den inn i Teams eller e-post, så ser de andre den samme filen.": "The link has been copied. Paste it into Teams or an email, and the others will see the same file.",
  "Programmet er ikke installert": "The app isn’t installed",
  "{0} er ikke installert på denne PC-en ennå. På en skole-PC henter du programmer fra Firmaportalen, ikke fra nettet. Vil du åpne Firmaportalen nå?": "{0} isn’t installed on this PC yet. On a school PC you get apps from the Company Portal, not from the internet. Do you want to open the Company Portal now?",
  "Åpne Firmaportalen": "Open Company Portal",
  "Ikke nå": "Not now",
  "Oppgaveark om brøk": "Worksheet on fractions",
  "Ukens oppgaver, 3 sider": "This week’s exercises, 3 pages",
  "Oppgaveark: Brøk\n\n1) Forkort 6/8\n2) Regn ut 1/2 + 1/4\n3) Hva er 3/5 av 40?": "Worksheet: Fractions\n\n1) Simplify 6/8\n2) Work out 1/2 + 1/4\n3) What is 3/5 of 40?",
  "Mal for rapport": "Report template",
  "Bruk denne når du skriver labrapport": "Use this when you write a lab report",
  "RAPPORT\n\nTittel:\nHensikt:\nUtstyr:\nFremgangsmåte:\nResultat:\nKonklusjon:": "REPORT\n\nTitle:\nAim:\nEquipment:\nMethod:\nResults:\nConclusion:",
  "Bilde til fortellingen": "Picture for the story",
  "Skogen om høsten": "The forest in autumn",
  "Presentasjon om demokrati": "Presentation on democracy",
  "Lysbildene fra timen": "The slides from the lesson",
  "Demokrati\nFolkestyre – alle over 18 år kan stemme.": "Democracy\nRule by the people – everyone over 18 can vote.",
  "Skoleportalen": "School Portal",
  "ovings-pc.simulering/skoleportalen/8a/oppgaver": "practice-pc.simulation/school-portal/8a/assignments",
  "8A · Ukeplan og oppgaver · Dette er en øvingsside i Datatrening, ikke en ekte nettside": "8A · Weekly plan and assignments · This is a practice page in Datatrening, not a real website",
  "Filer fra lærerne": "Files from your teachers",
  "Klikk «Last ned» for å hente en fil. Filen havner i mappen <b>Nedlastinger</b> på PC-en.": "Click “Download” to get a file. The file ends up in the <b>Downloads</b> folder on the PC.",
  "Last ned": "Download",
  "Åpne lenke i ny fane": "Open link in new tab",
  "På en ekte PC åpnes lenken i en ny fane.": "On a real PC the link opens in a new tab.",
  "Lagre lenke som …": "Save link as…",
  "ovings-pc.simulering/skoleportalen/filer/{0}": "practice-pc.simulation/school-portal/files/{0}",
  "Lenken er kopiert.": "The link has been copied.",
  "nedlastingslenken «{0}»": "the download link “{0}”",
  "Skoleportalen – Nettleser": "School Portal – Browser",
  "Siden ble lastet på nytt.": "The page was reloaded.",
  "Lagre som …": "Save as…",
  "Dette lagrer hele nettsiden som en fil. Det trenger du sjelden.": "This saves the whole web page as a file. You’ll rarely need that.",
  "Skriv ut …": "Print…",
  "Utskrift av nettsiden (simulert).": "Printing the web page (simulated).",
  "Vis sidekilde": "View page source",
  "Sidekilden er koden bak nettsiden (HTML).": "The page source is the code behind the web page (HTML).",
  "nettsiden": "the web page",
  "Lagret «{0}» i {1}": "Saved “{0}” in {1}",
  "Ingen nedlastinger ennå.": "No downloads yet.",
  "Ferdig · lagret i Nedlastinger<br><a class=\"op\">Åpne fil</a><a class=\"sh\">Vis i mappe</a>": "Done · saved in Downloads<br><a class=\"op\">Open file</a><a class=\"sh\">Show in folder</a>",
  "Filen er flyttet eller slettet": "The file has been moved or deleted",
  "Dikt-analyse": "Poem analysis",
  "fredag 25. september": "Friday 25 September",
  "Lever dikt-analysen din som et Word-dokument. Husk å gi filen et tydelig navn.": "Hand in your poem analysis as a Word document. Remember to give the file a clear name.",
  "Brøk-oppgaver": "Fraction exercises",
  "mandag 28. september": "Monday 28 September",
  "Lever det utfylte oppgavearket om brøk (PDF).": "Hand in the completed worksheet on fractions (PDF).",
  "Rapport: Fotosyntese": "Report: Photosynthesis",
  "onsdag 30. september": "Wednesday 30 September",
  "Lever labrapporten din. Bruk malen fra Skoleportalen.": "Hand in your lab report. Use the template from the School Portal.",
  "Oppgaver": "Assignments",
  "Frist: {0}": "Due: {0}",
  "✓ Levert": "✓ Handed in",
  "✓ Levert {0}": "✓ Handed in {0}",
  "Velg en oppgave i listen til venstre.": "Choose an assignment from the list on the left.",
  "Mitt arbeid": "My work",
  "Ingen filer lagt til ennå.": "No files added yet.",
  "Fjern": "Remove",
  "Angre innlevering": "Undo hand-in",
  "+ Legg til arbeid": "+ Add work",
  "Legg til arbeid – velg en fil": "Add work – choose a file",
  "Filen er allerede lagt til.": "That file has already been added.",
  "Du kan legge ved maks 10 filer per oppgave.": "You can attach up to 10 files per assignment.",
  "Lever inn": "Hand in",
  "Innlevert! Læreren kan nå se arbeidet ditt.": "Handed in! Your teacher can now see your work.",
  "Dette er en PDF-fil. En PDF ser lik ut på alle enheter og kan vanligvis ikke redigeres.": "This is a PDF file. A PDF looks the same on every device and usually can’t be edited.",
  "Lysbilde 1 av 12": "Slide 1 of 12",
  "Post": "Item",
  "Beløp": "Amount",
  "Buss": "Coach",
  "Overnatting": "Accommodation",
  "Mat": "Food",
  "Sum": "Total",
  "<b>Plassering:</b> {0} · <b>Størrelse:</b> {1}<br>På en ekte PC åpnes denne filtypen (.{2}) i <b>{3}</b>.": "<b>Location:</b> {0} · <b>Size:</b> {1}<br>On a real PC this file type (.{2}) opens in <b>{3}</b>.",
  "Vis filendelser i Filutforsker": "Show file name extensions in File Explorer",
  "Viser .docx, .pdf osv. bak filnavnet.": "Shows .docx, .pdf etc. after the file name.",
  "Sletter alle filer og mapper du har laget, og legger tilbake de opprinnelige filene. Fremdriften din beholdes.": "Deletes all the files and folders you’ve made and puts the original files back. Your progress is kept.",
  "Tilbakestill": "Reset",
  "Fjerner alle fullførte oppdrag og starter fra begynnelsen.": "Removes all completed tasks and starts from the beginning.",
  "Nullstill": "Clear",
  "Er du sikker? Alle filer og mapper du har laget blir borte.": "Are you sure? All the files and folders you’ve made will be gone.",
  "Øvings-PC-en er tilbakestilt.": "The practice PC has been reset.",
  "Er du sikker? All fremdrift blir slettet.": "Are you sure? All your progress will be deleted.",
  "Prosesser": "Processes",
  "På en ekte PC åpner du Oppgavebehandling med <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Esc</kbd>, eller ved å høyreklikke på oppgavelinjen. Her kan du avslutte programmer som har hengt seg.": "On a real PC you open Task Manager with <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Esc</kbd>, or by right-clicking the taskbar. Here you can end apps that have stopped responding.",
  "Avslutt oppgave": "End task",
  "Ingen andre programmer kjører.": "No other apps are running.",
  "Svart": "Black",
  "Rød": "Red",
  "Blå": "Blue",
  "Grønn": "Green",
  "Lilla": "Purple",
  "Oransje": "Orange",
  "Dokument{0}": "Document{0}",
  "<kbd>Ctrl</kbd>+<kbd>S</kbd> lagre · <kbd>Ctrl</kbd>+<kbd>B</kbd> fet · <kbd>Ctrl</kbd>+<kbd>P</kbd> skriv ut": "<kbd>Ctrl</kbd>+<kbd>S</kbd> save · <kbd>Ctrl</kbd>+<kbd>B</kbd> bold · <kbd>Ctrl</kbd>+<kbd>P</kbd> print",
  "Skrifttype": "Font",
  "Skriftstørrelse (punkt)": "Font size (points)",
  "Fet (Ctrl+B)": "Bold (Ctrl+B)",
  "Kursiv (Ctrl+I)": "Italic (Ctrl+I)",
  "Understreket (Ctrl+U)": "Underline (Ctrl+U)",
  "Tekstfarge": "Font colour",
  "Stil": "Style",
  "Normal": "Normal",
  "Overskrift 1": "Heading 1",
  "Overskrift 2": "Heading 2",
  "Venstrejuster": "Align left",
  "Midtstill": "Centre",
  "Høyrejuster": "Align right",
  "Punktliste": "Bullets",
  "Nummerert liste": "Numbering",
  "{0} ord": "{0} words",
  "1 ord": "1 word",
  "Lagret i: {0}": "Saved in: {0}",
  "Ikke lagret ennå": "Not saved yet",
  "🔄 Autolagrer …": "🔄 AutoSaving…",
  "☁ Autolagret i OneDrive": "☁ AutoSaved to OneDrive",
  "⚠ Ikke lagret (Ctrl+S)": "⚠ Not saved (Ctrl+S)",
  "💾 Lagret lokalt · ingen autolagring": "💾 Saved locally · no AutoSave",
  "Dokumentet er fullt (maks {0} tegn).": "The document is full (max {0} characters).",
  "Nettleseren tillater ikke liming fra menyen her. Bruk Ctrl+V.": "The browser doesn’t allow pasting from the menu here. Use Ctrl+V.",
  "Bruk Ctrl+V for å lime inn.": "Use Ctrl+V to paste.",
  "Merk alt": "Select All",
  "Formatering": "Formatting",
  "Fet": "Bold",
  "Kursiv": "Italic",
  "Understreket": "Underline",
  "teksten i Skriv": "the text in Write",
  "Kunne ikke lagre": "Couldn’t save",
  "Lagret: {0}": "Saved: {0}",
  "Word-dokument (*.docx)": "Word Document (*.docx)",
  "Tekstdokument (*.txt)": "Text Document (*.txt)",
  "Skriver:": "Printer:",
  "Skolens skriver (Kopirom 2. etasje)": "School printer (copy room, first floor)",
  "Microsoft Print to PDF (lag PDF-fil)": "Microsoft Print to PDF (make a PDF file)",
  "Eksemplarer:": "Copies:",
  "Dokumentet er på 1 side.": "The document is 1 page long.",
  "Dokumentet er på {0} sider.": "The document is {0} pages long.",
  "Velger du «Print to PDF», lages det en PDF-fil på PC-en i stedet for papir. PDF ser lik ut overalt og kan ikke redigeres.": "If you choose “Print to PDF”, a PDF file is made on the PC instead of paper. A PDF looks the same everywhere and can’t be edited.",
  "Sendt til skriveren (1 eksemplar). Hent utskriften i kopirommet.": "Sent to the printer (1 copy). Collect your printout in the copy room.",
  "Sendt til skriveren ({0} eksemplarer). Hent utskriften i kopirommet.": "Sent to the printer ({0} copies). Collect your printout in the copy room.",
  "Lagre PDF som": "Save PDF As",
  "PDF-dokument (*.pdf)": "PDF Document (*.pdf)",
  "PDF-filen «{0}» ble lagret i {1}.": "The PDF file “{0}” was saved in {1}.",
  "Kari (skriver nå): Jeg la til et avsnitt om kildene våre her.": "Kari (typing now): I added a paragraph about our sources here.",
  "Kari redigerer dokumentet samtidig som deg. Dere ser endringene til hverandre med én gang.": "Kari is editing the document at the same time as you. You see each other’s changes straight away.",
  "Dokumenter (*.docx, *.txt)": "Documents (*.docx, *.txt)",

  /* Notes, Mail, Typing Practice and Company Portal */
  "Skolen min": "My School",
  "Velkommen": "Welcome",
  "<div>Dette er en <b>side</b> i notatblokken din.</div><div><br></div><div>Til venstre ser du <b>inndelinger</b> (ett fag hver). I midten ser du <b>sidene</b> i inndelingen du har valgt.</div>": "<div>This is a <b>page</b> in your notebook.</div><div><br></div><div>On the left you can see the <b>sections</b> (one for each subject). In the middle you can see the <b>pages</b> in the section you have chosen.</div>",
  "Brøk": "Fractions",
  "<div>Forkorte brøk: del teller og nevner på det samme tallet.</div>": "<div>Simplifying fractions: divide the numerator and the denominator by the same number.</div>",
  "Søk i notatblokken": "Search notebook",
  "+ Ny inndeling": "+ Add section",
  "+ Ny side": "+ Add page",
  "Sidetittel": "Page title",
  "<b>F</b>": "<b>B</b>",
  "<i>K</i>": "<i>I</i>",
  "• liste": "• list",
  "Avkryssingsboks": "To Do tag",
  "☐ huskeliste": "☐ to-do",
  "Notater lagrer av seg selv. Du trenger ikke trykke Ctrl+S.": "Notes saves by itself. You don't need to press Ctrl+S.",
  "Ny inndeling": "New section",
  "Ny side": "New page",
  "notatblokken": "the notebook",
  "Lagres automatisk · sist endret {0}": "Saved automatically · last changed {0}",
  "Ny side i denne inndelingen": "New page in this section",
  "Gi nytt navn …": "Rename …",
  "Nytt navn på inndelingen:": "New name for the section:",
  "Skriv et navn.": "Type a name.",
  "Endre farge": "Section colour",
  "Farge {0}": "Colour {0}",
  "Slett inndelingen": "Delete section",
  "Notatblokken må ha minst én inndeling.": "The notebook must have at least one section.",
  "Slett inndeling": "Delete section",
  "Slette «{0}» med {1} side(r)? Dette kan ikke angres.": "Delete “{0}” with {1} page(s)? This can’t be undone.",
  "inndelingen «{0}»": "the section “{0}”",
  "Uten tittel": "Untitled page",
  "Ny tittel på siden:": "New title for the page:",
  "Skriv en tittel.": "Type a title.",
  "Flytt til inndeling": "Move to section",
  "«{0}» ble flyttet til {1}.": "“{0}” was moved to {1}.",
  "Slett siden": "Delete page",
  "Slett side": "Delete page",
  "Slette «{0}»? Dette kan ikke angres.": "Delete “{0}”? This can’t be undone.",
  "siden «{0}»": "the page “{0}”",
  "<div class=\"note-empty\">Ingen sider ennå.<br>Klikk «Ny side».</div>": "<div class=\"note-empty\">No pages yet.<br>Click “New page”.</div>",
  "Navn på inndelingen (for eksempel et fag):": "Name of the section (for example a subject):",
  "Notatblokken kan ha maks 20 inndelinger.": "The notebook can have at most 20 sections.",
  "Lag en inndeling først.": "Make a section first.",
  "En inndeling kan ha maks 50 sider.": "A section can have at most 50 pages.",
  "Tittel på siden:": "Title of the page:",
  "Søk: «{0}» · {1} treff": "Search: “{0}” · {1} results",
  "<div class=\"note-empty\">Ingen treff.</div>": "<div class=\"note-empty\">No results.</div>",
  "Kari Hansen (lærer)": "Kari Hansen (teacher)",
  "Mal for bokrapport": "Book report template",
  "Hei!\n\nHer er malen dere skal bruke til bokrapporten. Last den ned, skriv i den, og lever i Teams innen fredag.\n\nHusk å lagre din egen kopi i OneDrive før du begynner å skrive.\n\nVennlig hilsen\nKari": "Hi!\n\nHere is the template you will use for your book report. Download it, write in it, and hand it in on Teams by Friday.\n\nRemember to save your own copy in OneDrive before you start writing.\n\nBest wishes\nKari",
  "BOKRAPPORT\n\nTittel:\nForfatter:\nHandling:\nHva jeg synes:": "BOOK REPORT\n\nTitle:\nAuthor:\nWhat happens:\nWhat I think:",
  "Skolens administrasjon": "School office",
  "Alle elever": "All students",
  "Ukeplan uke 39": "Weekly plan week 39",
  "Ukeplanen for uke 39 ligger vedlagt.\n\nHusk gymtøy på tirsdag.": "The weekly plan for week 39 is attached.\n\nRemember your PE kit on Tuesday.",
  "Ukeplan uke 39\n\nMandag: Norsk, Matte\nTirsdag: Gym, Naturfag\nOnsdag: Engelsk": "Weekly plan week 39\n\nMonday: Norwegian, Maths\nTuesday: PE, Science\nWednesday: English",
  "Gruppeoppgave i samfunnsfag": "Group project in social studies",
  "Hei!\n\nKan du sende meg delen din av gruppeoppgaven? Jeg setter alt sammen i kveld.\n\nJonas": "Hi!\n\nCan you send me your part of the group project? I'm putting it all together tonight.\n\nJonas",
  "✉ Ny melding": "✉ New mail",
  "📥 Innboks": "📥 Inbox",
  "📤 Sendt": "📤 Sent Items",
  "<div class=\"mail-empty\">Ingen meldinger her.</div>": "<div class=\"mail-empty\">No messages here.</div>",
  "Til: {0}": "To: {0}",
  "(uten emne)": "(no subject)",
  "<div class=\"mail-empty\">Velg en melding i listen.</div>": "<div class=\"mail-empty\">Select a message in the list.</div>",
  "<div class=\"mr-attach\"><b>📎 Vedlegg</b></div>": "<div class=\"mr-attach\"><b>📎 Attachments</b></div>",
  "<button class=\"btn small\">Lagre som …</button>": "<button class=\"btn small\">Save as …</button>",
  "<button class=\"btn small\">Åpne</button>": "<button class=\"btn small\">Open</button>",
  "<div class=\"muted\" style=\"margin-top:6px\">Et vedlegg ligger i meldingen, ikke på PC-en din. Vil du beholde det, må du lagre det i en mappe.</div>": "<div class=\"muted\" style=\"margin-top:6px\">An attachment is inside the message, not on your PC. If you want to keep it, you have to save it in a folder.</div>",
  "<button class=\"btn primary\">↩ Svar</button>": "<button class=\"btn primary\">↩ Reply</button>",
  "SV: {0}": "RE: {0}",
  "<button class=\"btn\">↩↩ Svar alle</button>": "<button class=\"btn\">↩↩ Reply all</button>",
  "<span class=\"muted\" style=\"margin-left:8px\">«Svar alle» går til alle som fikk meldingen. Bruk det bare når alle trenger svaret.</span>": "<span class=\"muted\" style=\"margin-left:8px\">“Reply all” goes to everyone who got the message. Only use it when everyone needs the answer.</span>",
  "Lagre vedlegg som": "Save attachment as",
  "Vedlegget ble lagret i {0}.": "The attachment was saved in {0}.",
  "Vedlegget ble åpnet fra en midlertidig kopi i Nedlastinger. Skal du beholde det, bruk «Lagre som».": "The attachment was opened from a temporary copy in Downloads. To keep it, use “Save as”.",
  "Til:": "To:",
  "Emne:": "Subject:",
  "Hva handler meldingen om?": "What is your message about?",
  "Melding:": "Message:",
  "Skriv meldingen her": "Write your message here",
  "\n\n--- Opprinnelig melding fra {0} ---\n": "\n\n--- Original message from {0} ---\n",
  "Vedlegg:": "Attachments:",
  "Ingen vedlegg": "No attachments",
  "📎 Legg ved fil …": "📎 Attach file …",
  "Legg ved fil": "Attach file",
  "Filen er allerede lagt ved.": "That file is already attached.",
  "Maks fem vedlegg.": "Five attachments at most.",
  "Svar": "Reply",
  "Ny melding": "New mail",
  "Send": "Send",
  "Skriv hvem meldingen skal til.": "Type who the message is for.",
  "E-postadressen må inneholde @ og et punktum, for eksempel navn@skolen.no": "The email address must contain @ and a full stop, for example navn@skolen.no",
  "Meg": "Me",
  "Meldingen ble sendt.": "Your message was sent.",
  "Hjemmeraden": "Home row",
  "asdf jklø asdf jklø fjas løkk asdf jklø sal dal fall skal ask lask das": "asdf jkl asdf jkl fads lads asdf jkl ask flask sad dad fall all lass salad",
  "Vanlige ord": "Common words",
  "og i det er en til at som på de med han av ikke for var meg seg men da mot": "the of and to a in is it you that he was for on are as with his they at be",
  "Setninger": "Sentences",
  "Jeg går på skolen hver dag. Vi lærer matte, norsk og naturfag. I dag skal vi skrive en tekst om høsten.": "I go to school every day. We learn maths, English and science. Today we are writing a text about autumn.",
  "Æ, Ø og Å": "Q, X and Z",
  "Måken fløy over åsen. Søsteren min spiser rødgrøt. Å være ærlig er viktig. Gården ligger ved sjøen.": "The quick brown fox jumps over the lazy dog. Zoe fixed six quiet jazz boxes. Max quickly zipped his coat.",
  "Store bokstaver og tegn": "Capitals and symbols",
  "Hei! Heter du Ola? Send meg en e-post på ola@skolen.no. Prisen er 249,50 kr (inkludert moms).": "Hi! Is your name Ola? Send me an email at ola@skolen.no. The price is £24.50 (including VAT).",
  "Øvelse:": "Exercise:",
  "Klikk her og begynn å skrive …": "Click here and start typing …",
  "Slik skriver du raskere:": "How to type faster:",
  "Plasser fingrene på <b>hjemmeraden</b>: venstre hånd på <kbd>a</kbd> <kbd>s</kbd> <kbd>d</kbd> <kbd>f</kbd>, høyre hånd på <kbd>j</kbd> <kbd>k</kbd> <kbd>l</kbd> <kbd>ø</kbd>. Tomlene hviler på mellomromstasten.": "Put your fingers on the <b>home row</b>: left hand on <kbd>a</kbd> <kbd>s</kbd> <kbd>d</kbd> <kbd>f</kbd>, right hand on <kbd>j</kbd> <kbd>k</kbd> <kbd>l</kbd> <kbd>;</kbd>. Your thumbs rest on the space bar.",
  "<kbd>F</kbd> og <kbd>J</kbd> har en liten kul du kan kjenne. Da finner du plassen uten å se ned.": "<kbd>F</kbd> and <kbd>J</kbd> have a little bump you can feel. That way you find your place without looking down.",
  "<b>Ikke se på tastaturet.</b> Det går saktere de første gangene, men mye raskere etterpå.": "<b>Don’t look at the keyboard.</b> It’s slower the first few times, but much faster afterwards.",
  "Skriv jevnt og riktig framfor fort. Hastigheten kommer av seg selv.": "Type steadily and correctly rather than fast. The speed will come by itself.",
  "{0} ord/min · {1} % riktig · {2} s": "{0} wpm · {1}% correct · {2} s",
  "{0} ord/min": "{0} words/min",
  "{0} % riktig · {1} sekunder": "{0}% correct · {1} seconds",
  "Prøv å skrive litt saktere og treffe riktig. Treffsikkerhet er viktigere enn fart.": "Try typing a bit more slowly and hitting the right keys. Accuracy matters more than speed.",
  "Bra treffsikkerhet! Nå kan du prøve å øke farten litt.": "Good accuracy! Now you can try to speed up a little.",
  "Bra jobbet! Fortsett å øve uten å se på tastaturet.": "Well done! Keep practising without looking at the keyboard.",
  "Veldig bra! Du skriver raskt og riktig.": "Brilliant! You type fast and accurately.",
  "Din beste på denne øvelsen: {0} ord/min": "Your best on this exercise: {0} words/min",
  "Heter «Kode» her på øvings-PC-en": "Called “Code” on this practice PC",
  "Program for å skrive kode. Brukes i programmeringsfaget.": "An app for writing code. Used in programming lessons.",
  "Programmeringsspråket Python, så du kan kjøre .py-filer.": "The Python programming language, so you can run .py files.",
  "Klasserom, meldinger og innleveringer.": "Classrooms, chat and assignments.",
  "Digital notatblokk med inndelinger og sider.": "A digital notebook with sections and pages.",
  "3,2 GB": "3.2 GB",
  "Skriveprogram, regneark og presentasjoner.": "Documents, spreadsheets and presentations.",
  "GeoGebra Klassisk": "GeoGebra Classic",
  "Geometri, algebra og grafer. Brukes i matte.": "Geometry, algebra and graphs. Used in maths.",
  "Enkel teksteditor med fargekoding.": "A simple text editor with colour coding.",
  "Leser PDF-filer.": "Opens PDF files.",
  "I kø …": "Pending …",
  "Laster ned …": "Downloading …",
  "Installerer …": "Installing …",
  "Mislyktes": "Failed",
  "Installert": "Installed",
  "Installasjonen av {0} mislyktes. Prøv igjen.": "Installing {0} failed. Try again.",
  "{0} er installert. Du finner programmet i Start-menyen.": "{0} is installed. You can find it in the Start menu.",
  "Alle": "All apps",
  "Skolens godkjente programmer · pålogget som elev@skolen.no": "Apps approved by your school · signed in as elev@skolen.no",
  "Søk etter et program": "Search for apps",
  "Programmer herfra er godkjent av skolen. Last aldri ned programmer fra nettet på skole-PC-en.": "Apps from here are approved by the school. Never download programs from the internet on a school PC.",
  "Fant ingen programmer{0}.": "No apps found{0}.",
  " som passer med «{0}»": " matching “{0}”",
  "Husk at et program heter det produsenten kaller det, ikke det vi kaller det til daglig. Prøv et kortere søkeord, eller bla i kategoriene til venstre.": "Remember: an app is called what its maker calls it, not what we call it every day. Try a shorter search word, or browse the categories on the left.",
  "<span class=\"fp-state ok\">✓ Installert</span>": "<span class=\"fp-state ok\">✓ Installed</span>",
  "Starter …": "Starting …",
  "<span class=\"fp-state bad\">✕ Mislyktes<br><span class=\"muted\">Feilkode 0x87D1041C</span></span>": "<span class=\"fp-state bad\">✕ Failed<br><span class=\"muted\">Error code 0x87D1041C</span></span>",
  "<button class=\"btn small primary\">Prøv igjen</button>": "<button class=\"btn small primary\">Retry</button>",
  "<button class=\"btn small primary\">Installer</button>": "<button class=\"btn small primary\">Install</button>",

  /* Terminal, Code and Python */
  "Get-Location (pwd)\n  Viser hvilken mappe du står i.": "Get-Location (pwd)\n  Shows which folder you are in.",
  "Set-Location (cd) <sti>\n  Bytter mappe.\n  cd Documents      gå inn i Documents\n  cd ..             ett nivå opp\n  cd ~              hjem (C:\\Users\\Elev)\n  cd \"Min mappe\"    navn med mellomrom må ha anførselstegn": "Set-Location (cd) <path>\n  Changes folder.\n  cd Documents      go into Documents\n  cd ..             up one level\n  cd ~              home (C:\\Users\\Student)\n  cd \"My folder\"    names with spaces need quotation marks",
  "Get-ChildItem (ls, dir) [sti]\n  Lister filer og mapper.\n  ls                mappen du står i\n  ls Documents      en annen mappe\n  ls *.py           bare Python-filer\n  ls -Name          bare navnene\n  ls -Recurse       også undermapper": "Get-ChildItem (ls, dir) [path]\n  Lists files and folders.\n  ls                the folder you are in\n  ls Documents      another folder\n  ls *.py           only Python files\n  ls -Name          only the names\n  ls -Recurse       subfolders too",
  "New-Item (ni) <navn>\n  Lager en ny fil.\n  New-Item hei.py\n  New-Item -ItemType Directory Kode   lager en mappe (eller bruk mkdir Kode)": "New-Item (ni) <name>\n  Creates a new file.\n  New-Item hello.py\n  New-Item -ItemType Directory Code   creates a folder (or use mkdir Code)",
  "mkdir <navn>\n  Lager en ny mappe.": "mkdir <name>\n  Creates a new folder.",
  "Remove-Item (rm, del) <sti>\n  Sletter en fil eller mappe. NB: i terminalen går det IKKE via papirkurven.\n  rm gammel.txt\n  rm -Recurse mappe    sletter mappen med alt innhold": "Remove-Item (rm, del) <path>\n  Deletes a file or folder. Note: in the terminal it does NOT go to the Recycle Bin.\n  rm old.txt\n  rm -Recurse folder   deletes the folder and everything in it",
  "Move-Item (mv) <fra> <til>\n  Flytter (eller gir nytt navn).\n  mv hei.py Kode\\       flytt inn i mappen Kode\n  mv hei.py hallo.py    nytt navn": "Move-Item (mv) <from> <to>\n  Moves (or renames).\n  mv hello.py Code\\     move into the folder Code\n  mv hello.py hi.py     new name",
  "Copy-Item (cp) <fra> <til>\n  Kopierer.\n  cp hei.py kopi.py\n  cp -Recurse Kode Kode2   kopier en hel mappe": "Copy-Item (cp) <from> <to>\n  Copies.\n  cp hello.py copy.py\n  cp -Recurse Code Code2   copy a whole folder",
  "Rename-Item (ren) <sti> <nytt navn>\n  Gir nytt navn.": "Rename-Item (ren) <path> <new name>\n  Renames.",
  "Get-Content (cat, type) <fil>\n  Viser innholdet i en fil.": "Get-Content (cat, type) <file>\n  Shows what is inside a file.",
  "Set-Content <fil> <tekst>\n  Skriver tekst til en fil (erstatter innholdet).": "Set-Content <file> <text>\n  Writes text to a file (replaces what was there).",
  "Add-Content <fil> <tekst>\n  Legger til tekst nederst i en fil.": "Add-Content <file> <text>\n  Adds text to the end of a file.",
  "Write-Output (echo) <tekst>\n  Skriver tekst til skjermen. Med > kan du sende den til en fil:\n  echo \"hei\" > fil.txt": "Write-Output (echo) <text>\n  Writes text to the screen. With > you can send it to a file:\n  echo \"hello\" > file.txt",
  "Write-Host <tekst>\n  Skriver tekst til skjermen (brukes i skript).": "Write-Host <text>\n  Writes text to the screen (used in scripts).",
  "Clear-Host (cls, clear)\n  Tømmer skjermen.": "Clear-Host (cls, clear)\n  Clears the screen.",
  "Get-Help (help) <kommando>\n  Viser hjelp for en kommando.": "Get-Help (help) <command>\n  Shows help for a command.",
  "Get-Alias (gal) [alias]\n  Viser hvilke kommandoer et kortnavn står for. ls = Get-ChildItem osv.": "Get-Alias (gal) [alias]\n  Shows which command a short name stands for. ls = Get-ChildItem and so on.",
  "Get-Command\n  Lister kommandoene som finnes.": "Get-Command\n  Lists the commands you can use.",
  "python <fil.py>\n  Kjører et Python-program.\n  python --version   viser versjonen": "python <file.py>\n  Runs a Python program.\n  python --version   shows the version",
  "code <mappe eller fil>\n  Åpner Kode-editoren.\n  code .        åpner mappen du står i\n  code hei.py   åpner en fil": "code <folder or file>\n  Opens the Code editor.\n  code .          opens the folder you are in\n  code hello.py   opens a file",
  "explorer <mappe>\n  Åpner Filutforsker.\n  explorer .    mappen du står i": "explorer <folder>\n  Opens File Explorer.\n  explorer .    the folder you are in",
  "tree\n  Tegner mappestrukturen som et tre.": "tree\n  Draws the folder structure as a tree.",
  "Test-Path <sti>\n  Svarer True hvis stien finnes, ellers False.": "Test-Path <path>\n  Answers True if the path exists, otherwise False.",
  "Select-String (sls) <tekst> <fil>\n  Søker etter tekst i filer. Kan også brukes etter |:\n  ls | Select-String py": "Select-String (sls) <text> <file>\n  Searches for text in files. Can also be used after |:\n  ls | Select-String py",
  "Measure-Object (measure)\n  Teller. ls | measure   teller elementer": "Measure-Object (measure)\n  Counts. ls | measure   counts items",
  "Get-Date\n  Viser dato og klokkeslett.": "Get-Date\n  Shows the date and time.",
  "exit\n  Lukker terminalen.": "exit\n  Closes the terminal.",
  "Øvings-terminalen (PowerShell)\n\nNavigasjon:   pwd, cd, ls, tree, explorer .\nFiler:        mkdir, New-Item, Remove-Item, Move-Item, Copy-Item, Rename-Item, Get-Content, Set-Content, echo \"tekst\" > fil\nProgrammer:   python fil.py, code ., .\\skript.ps1, notepad fil.txt\nAnnet:        Get-Help <kommando>, Get-Alias, cls, exit\n\nTips: Tab fullfører navn. Pil opp henter forrige kommando. Ctrl+C stopper et program som kjører.": "The practice terminal (PowerShell)\n\nGetting around: pwd, cd, ls, tree, explorer .\nFiles:          mkdir, New-Item, Remove-Item, Move-Item, Copy-Item, Rename-Item, Get-Content, Set-Content, echo \"text\" > file\nPrograms:       python file.py, code ., .\\script.ps1, notepad file.txt\nOther:          Get-Help <command>, Get-Alias, cls, exit\n\nTip: Tab completes names. Up arrow brings back the last command. Ctrl+C stops a program that is running.",
  "PowerShell 7.4.2 (øvings-terminal)\nSkriv help for å se kommandoene du kan bruke.\n": "PowerShell 7.4.2 (practice terminal)\nType help to see the commands you can use.\n",
  "Tøm skjermen": "Clear screen",
  "Hjelp (help)": "Help (help)",
  "terminalen": "the terminal",
  "Tips: Python-filer kjøres med:  python {0}\n": "Tip: Python files are run with:  python {0}\n",
  "Åpne den med: code {0}": "Open it with: code {0}",
  "Denne mappen hører til systemet.": "This folder belongs to the system.",
  "{0}: Mappen «{1}» ble kopiert uten innhold. Bruk -Recurse for å ta med filene i den.\n": "{0}: The folder '{1}' was copied without its contents. Use -Recurse to include the files in it.\n",
  "Det er en mappe, ikke en fil.": "It is a folder, not a file.",
  "Get-Help: Fant ingen hjelp for «{0}». Skriv help for en oversikt.": "Get-Help: No help found for '{0}'. Type help for an overview.",
  "Select-String: Angi en fil å søke i, eller bruk kommandoen etter | (f.eks. ls | Select-String py).": "Select-String: Give a file to search in, or use the command after | (e.g. ls | Select-String py).",
  "Python 3.12.4 (øvings-PC)\nInteraktiv modus støttes ikke her. Kjør en fil:  python fil.py": "Python 3.12.4 (practice PC)\nInteractive mode is not supported here. Run a file:  python file.py",
  "Tips: Visual Studio Code er ikke installert på denne PC-en. Åpne Firmaportalen og installer det derfra.": "Tip: Visual Studio Code is not installed on this PC. Open the Company Portal and install it from there.",
  "Kode-editoren finnes bare på programmeringssiden.": "The Code editor is only available on the programming page.",
  "\n[Øvings-PC: programmet ble stoppet etter 5 millioner steg. Har du en løkke som aldri slutter?]\n": "\n[Practice PC: the program was stopped after 5 million steps. Do you have a loop that never ends?]\n",
  "\n[Øvings-PC: programmet skrev ut mer enn 5000 linjer og ble stoppet. Bruk Ctrl+C for å stoppe programmer som kjører evig.]\n": "\n[Practice PC: the program printed more than 5000 lines and was stopped. Use Ctrl+C to stop programs that run forever.]\n",
  "{0}: linje {1}: «{2}» støttes ikke i øvings-terminalen. Bruk Write-Host, Read-Host, variabler og vanlige kommandoer.\n": "{0}: line {1}: '{2}' is not supported in the practice terminal. Use Write-Host, Read-Host, variables and ordinary commands.\n",
  "Terminalen kjører allerede et program. Stopp det med Ctrl+C først.": "The terminal is already running a program. Stop it with Ctrl+C first.",
  "Ren tekst": "Plain Text",
  "Ny fil": "New File",
  "Åpne mappe": "Open Folder",
  "<kbd>Ctrl</kbd>+<kbd>S</kbd> lagrer · <kbd>Tab</kbd> = 4 mellomrom": "<kbd>Ctrl</kbd>+<kbd>S</kbd> saves · <kbd>Tab</kbd> = 4 spaces",
  "Kjør filen i terminalen": "Run file in terminal",
  "▶ Kjør": "▶ Run",
  "UTFORSKER": "EXPLORER",
  "Åpne en mappe med <code>code .</code> i terminalen, eller lag en ny fil.": "Open a folder with <code>code .</code> in the terminal, or create a new file.",
  "Kommenter ut / inn": "Toggle Line Comment",
  "Kjør filen": "Run File",
  "koden i Kode": "the code in Code",
  "Filen finnes ikke lenger.": "The file no longer exists.",
  "Åpne en fil først.": "Open a file first.",
  "Bare .py og .ps1 kan kjøres. Filen er .{0}": "Only .py and .ps1 files can be run. This file is .{0}",
  "Velg mappe for den nye filen": "Choose a folder for the new file",
  "Filnavn (for eksempel hei.py):": "File name (for example hello.py):",
  "Det finnes allerede en fil med dette navnet.": "There is already a file with this name.",
  "Ta med filendelsen, for eksempel .py": "Include the file extension, for example .py",
  "Åpne en mappe først.": "Open a folder first.",
  "Mappenavn:": "Folder name:",
  "Ingen mappe er åpnet.<br><br>Skriv <code>code .</code> i terminalen, eller klikk «Åpne mappe».": "You have not yet opened a folder.<br><br>Type <code>code .</code> in the terminal, or click 'Open Folder'.",
  "Ny fil …": "New File...",
  "Ny mappe …": "New Folder...",
  "Åpne i terminal": "Open in Integrated Terminal",
  "Vis i Filutforsker": "Reveal in File Explorer",
  "Nytt navn:": "New name:",
  "Flytte mappen «{0}» til papirkurven?": "Move the folder '{0}' to the Recycle Bin?",
  "mappen i Kode-utforskeren": "the folder in the Code Explorer",
  "Kjør i terminalen": "Run in Terminal",
  "Kopier sti": "Copy Path",
  "Kopierte: {0}": "Copied: {0}",
  "Flytte «{0}» til papirkurven?": "Move '{0}' to the Recycle Bin?",
  "filen i Kode-utforskeren": "the file in the Code Explorer",
  "Lukk alle": "Close All",
  "fanen i Kode": "the tab in Code",
  "Hjelp: se kurset i veilederen til høyre. Innebygde funksjoner: print, input, int, float, str, len, range, list, abs, round, min, max, sum, sorted, open\n": "Help: see the course in the guide on the right. Built-in functions: print, input, int, float, str, len, range, list, abs, round, min, max, sum, sorted, open\n"
});
